name: ubuntu-frame-osk
summary: On-screen keyboard for Ubuntu Frame, based on Squeekboard
description: This snap contains the Wayland on-screen keyboard Squeekboard, modified and packaged such that it can run on Ubuntu Frame.
confinement: strict
base: core24
adopt-info: squeekboard
license: GPL-3.0
compression: lzo
grade: stable

platforms:
  amd64:
  arm64:
  armhf:
  riscv64:

plugs:
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404
  squeekboard-layouts:
    interface: content
    target: $SNAP_COMMON/squeekboard/keyboards

environment:
  SQUEEKBOARD_KEYBOARDSDIR: $SNAP_COMMON/squeekboard/keyboards
  XDG_DATA_DIRS: $SNAP/usr/share:$SNAP/usr/local/share
  # XKB config from snap
  XKB_CONFIG_ROOT: $SNAP/usr/share/X11/xkb
  FONTCONFIG_PATH: $SNAP/etc/fonts
  FONTCONFIG_FILE: $SNAP/etc/fonts/fonts.conf

layout:
  /usr/share/drirc.d:  # Used by mesa-2404 for app specific workarounds
    symlink: $SNAP/gpu-2404/drirc.d
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/themes:
    symlink: $SNAP/usr/share/themes
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0
  /usr/share/mime:
    symlink: $SNAP/usr/share/mime
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/share/xml:
    bind: $SNAP/usr/share/xml
  /usr/share/glib-2.0:
    bind: $SNAP/usr/share/glib-2.0

apps:
  ubuntu-frame-osk:
    command-chain: &_command-chain
      - bin/wayland-launch
      - bin/run-user
      - bin/anon-shm-preload
      - bin/gpu-2404-wrapper
    command: &_command usr/bin/squeekboard
    plugs: &_plugs [wayland]

  daemon:
    daemon: simple
    restart-delay: 3s
    restart-condition: always
    command-chain: *_command-chain
    command: *_command
    plugs: *_plugs

  list-layouts:
    command: usr/bin/list-layouts

parts:
  scripts:
    plugin: dump
    source: scripts

  anon-shm-preload:
        source: https://github.com/canonical/anon-shm-preload.git
        plugin: cmake

  # Some utility scripts for setting up the Wayland environment
  wayland-launch:
    plugin: dump
    source: wayland-launch
    stage-packages:
      - inotify-tools

  list-layouts:
    source: list-layouts
    plugin: meson
    build-packages:
      - meson
      - libgnome-desktop-3-dev
    stage-packages:
      - libgnome-desktop-3-20t64

  squeekboard-patches:
    plugin: dump
    source: patches
    prime:
      - -squeekboard-patches

  squeekboard:
    after: [squeekboard-patches]
    plugin: meson
    source: https://git.launchpad.net/ubuntu/+source/squeekboard
    source-type: git
    source-tag: applied/1.43.1-1
    source-depth: 1
    override-pull: |
      craftctl default
      recipe_version=`git -C ${CRAFT_PROJECT_DIR} rev-list --count HEAD`
      craftctl set version=$recipe_version-sb1.43.1-1
    meson-parameters: [--prefix, /usr, -Dstrict=false, -Dbuildtype=release]
    override-build: |
      git -C ${CRAFT_PART_SRC} apply ${CRAFT_STAGE}/squeekboard-patches/*
      craftctl default
      # Generate a list of keyboard layouts
      mkdir -p ${CRAFT_PART_INSTALL}/etc
      ls ${CRAFT_PART_SRC}/data/keyboards/ \
        | grep -Po '^[a-zA-Z\+]+(?=.*\.yaml$)' \
        | sort | uniq \
        >${CRAFT_PART_INSTALL}/etc/layouts.txt
    build-packages:
      - cargo
      - meson
      - wayland-protocols
      - libbsd-dev
      - libfeedback-dev
      - libwayland-dev
      - libglib2.0-dev
      - libgnome-desktop-3-dev
      - libgtk-3-dev
      - gettext
    stage-packages:
      - libbsd0
      - libfeedback-0.0-0
      - libglib2.0-0t64
      - libgnome-desktop-3-20t64
      - libgtk-3-0t64
      - yaru-theme-gtk
      - iso-codes
      - xkb-data
    prime:
      - -usr/bin/squeekboard-test-layout

  gtk-prep:
    after: [squeekboard]
    plugin: nil
    build-packages:
      - librsvg2-2
      - libgdk-pixbuf2.0-0
      - shared-mime-info
    stage-packages:
      - librsvg2-common
      - gsettings-desktop-schemas
      - libglib2.0-bin
    override-build: |
      # Update mime database
      update-mime-database ${CRAFT_PART_INSTALL}/usr/share/mime
    override-prime: |
      craftctl default
      # Compile the gsettings schemas
      /usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/glib-2.0/glib-compile-schemas ${CRAFT_PRIME}/usr/share/glib-2.0/schemas
      # Index the pixbuf loaders
      LOADERS_PATH=$(echo ${CRAFT_PRIME}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gdk-pixbuf-2.0/*/loaders)
      QUERY_LOADERS=/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders
      GDK_PIXBUF_MODULEDIR=${LOADERS_PATH} ${QUERY_LOADERS} > ${LOADERS_PATH}/../loaders.cache
      sed s!$CRAFT_PRIME!!g --in-place ${LOADERS_PATH}/../loaders.cache

  fonts:
    plugin: nil
    stage-packages:
      - fonts-noto-color-emoji
      - fonts-freefont-ttf
      - fonts-droid-fallback

  gpu-snap:
    after: [gtk-prep, wayland-launch, fonts]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
      rm -rf ${CRAFT_PRIME}/{alsa,dbus-1,help,apport,doc,doc-base,pkgconfig,thumbnailers,bash-completion,feedbackd,gir-1.0,libthai,sounds}
    prime:
      - bin/gpu-2404-wrapper
