name: ubuntu-frame-osk
summary: On-screen keyboard for Ubuntu Frame, based on Squeekboard
description: This snap contains the Wayland on-screen keyboard Squeekboard, modified and packaged such that it can run on Ubuntu Frame.
confinement: strict
base: core20
adopt-info: squeekboard
license: GPL-3.0
compression: lzo
grade: stable

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

plugs:
  graphics-core20:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core20

environment:
  # Graphics from graphics-core20
  LD_LIBRARY_PATH:    $SNAP/graphics/lib
  LIBGL_DRIVERS_PATH: $SNAP/graphics/dri
  LIBVA_DRIVERS_PATH: $SNAP/graphics/dri
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/graphics/glvnd/egl_vendor.d
  # XKB config from snap
  XKB_CONFIG_ROOT: $SNAP/usr/share/X11/xkb

layout:
  /usr/share/libdrm:  # Needed by mesa-core20 on AMD GPUs
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:  # Used by mesa-core20 for app specific workarounds
    bind: $SNAP/graphics/drirc.d
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/themes:
    bind: $SNAP/usr/share/themes
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0
  /usr/share/mime:
    bind: $SNAP/usr/share/mime
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/share/xml:
    bind: $SNAP/usr/share/xml
  /etc/fonts: # Without this emojis don't look right
    bind: $SNAP/etc/fonts
  /usr/share/glib-2.0:
    bind: $SNAP/usr/share/glib-2.0

apps:
  ubuntu-frame-osk:
    command-chain: &_command-chain [bin/wayland-launch, bin/run-user, bin/anon-shm-preload]
    command: &_command usr/bin/squeekboard
    plugs: &_plugs [wayland]

  daemon:
    daemon: simple
    restart-delay: 3s
    restart-condition: always
    command-chain: *_command-chain
    command: *_command
    plugs: *_plugs

  list-layouts:
    command: usr/bin/list-layouts

parts:
  recipe-version:
    plugin: nil
    source: .
    source-type: git
    override-build: |
      git rev-list --count HEAD > $SNAPCRAFT_PART_INSTALL/recipe-version
    prime:
      - -recipe-version

  scripts:
    plugin: dump
    source: scripts

  anon-shm-preload:
        source: https://github.com/MirServer/anon-shm-preload.git
        plugin: cmake

  # Some utility scripts for setting up the Wayland environment
  wayland-launch:
    plugin: dump
    source: wayland-launch
    override-build: |
      # The plugs needed to run Wayland. (wayland-launch checks them, setup.sh connects them)
      # You may add further plugs here if you want these options
      PLUGS="wayland graphics-core20"
      sed --in-place "s/%PLUGS%/$PLUGS/g" $SNAPCRAFT_PART_BUILD/bin/wayland-launch
      sed --in-place "s/%PLUGS%/$PLUGS/g" $SNAPCRAFT_PART_BUILD/bin/setup.sh
      sed --in-place "s/%SNAP%/$SNAPCRAFT_PROJECT_NAME/g" $SNAPCRAFT_PART_BUILD/bin/wayland-launch
      sed --in-place "s/%SNAP%/$SNAPCRAFT_PROJECT_NAME/g" $SNAPCRAFT_PART_BUILD/bin/setup.sh
      snapcraftctl build
    stage-packages:
      - inotify-tools

  list-layouts:
    source: list-layouts
    plugin: meson
    build-packages:
      - libgnome-desktop-3-dev
    stage-packages:
      - libgnome-desktop-3-19

  libfeedback:
    # Required by squeekboard because libfeedback-dev isn't in 20.04
    plugin: meson
    source: https://source.puri.sm/Librem5/feedbackd.git
    source-tag: v0.0.1
    source-depth: 1
    meson-parameters: [--prefix, /usr]
    build-packages:
      - dbus
      - libgirepository1.0-dev
      - libgudev-1.0-dev
      - libgsound-dev
      - libjson-glib-dev
      - valac
      - libglib2.0-dev
    stage-packages:
      - libgudev-1.0-0
      - libgsound0
      - libjson-glib-1.0-0
      - libglib2.0-0

  squeekboard-patches:
    plugin: dump
    source: patches
    prime:
      - -squeekboard-patches

  squeekboard:
    after: [libfeedback, squeekboard-patches, recipe-version]
    plugin: meson
    source: https://gitlab.gnome.org/World/Phosh/squeekboard.git
    source-tag: v1.17.1
    source-depth: 1
    override-pull: |
      snapcraftctl pull
      git apply ${SNAPCRAFT_STAGE}/squeekboard-patches/*
      recipe_version=`cat $SNAPCRAFT_STAGE/recipe-version`
      snapcraftctl set-version $recipe_version-squeekboard-`git describe`
    meson-parameters: [--prefix, /usr, -Dstrict=false, -Dbuildtype=release]
    override-build: |
      snapcraftctl build
      # Generate a list of keyboard layouts
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/etc
      ls ${SNAPCRAFT_PART_SRC}/data/keyboards/ \
        | grep -Po '^[a-zA-Z\+]+(?=.*\.yaml$)' \
        | sort | uniq \
        >${SNAPCRAFT_PART_INSTALL}/etc/layouts.txt
    build-packages:
      - cargo
      - wayland-protocols
      - libwayland-dev
      - libglib2.0-dev
      - libgnome-desktop-3-dev
      - libgtk-3-dev
      - gettext
    stage-packages:
      - libglib2.0-0
      - libgnome-desktop-3-19
      - libgtk-3-0
      - yaru-theme-gtk
      - iso-codes
    prime:
      - -usr/bin/squeekboard-test-layout

  gtk-prep:
    after: [squeekboard, libfeedback]
    plugin: nil
    build-packages:
      - libgdk-pixbuf2.0-0
      - shared-mime-info
    stage-packages:
      - librsvg2-common
      - gsettings-desktop-schemas
      - libglib2.0-bin
    override-build: |
      # Update mime database
      update-mime-database ${SNAPCRAFT_PART_INSTALL}/usr/share/mime
    override-prime: |
      snapcraftctl prime
      # Compile the gsettings schemas
      /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/glib-2.0/glib-compile-schemas ${SNAPCRAFT_PRIME}/usr/share/glib-2.0/schemas
      # Index the pixbuf loaders
      LOADERS_PATH=$(echo ${SNAPCRAFT_PRIME}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/gdk-pixbuf-2.0/*/loaders)
      QUERY_LOADERS=/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders
      GDK_PIXBUF_MODULEDIR=${LOADERS_PATH} ${QUERY_LOADERS} > ${LOADERS_PATH}/../loaders.cache
      sed s!$SNAPCRAFT_PRIME!!g --in-place ${LOADERS_PATH}/../loaders.cache

  fonts:
    plugin: nil
    stage-packages:
      - fonts-noto-color-emoji
      - fonts-freefont-ttf
      - fonts-droid-fallback

  cleanup:
    after: [gtk-prep, wayland-launch, fonts]
    plugin: nil
    build-snaps: [ mesa-core20 ]
    override-prime: |
      set -eux
      cd /snap/mesa-core20/current/egl/lib
      find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/{} \;
      rm -fr "$SNAPCRAFT_PRIME/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri"
      cd "$SNAPCRAFT_PRIME/usr/share"
      rm -rf bug drirc.d glvnd libdrm lintian man

  more-cleanup:
    after: [cleanup]
    plugin: nil
    override-prime: |
      set -eux
      cd "$SNAPCRAFT_PRIME/usr/share"
      rm -rf alsa dbus-1 help apport doc doc-base pkgconfig thumbnailers bash-completion feedbackd gir-1.0 libthai sounds
