#!/bin/sh
set -eux

# Clear out osk-auth and allow all users to create files in it
OSK_AUTH="$SNAP_DATA/osk-auth"
mkdir -p "$OSK_AUTH"
rm -f "$OSK_AUTH/allow-*"
chmod a=rwx "$OSK_AUTH"

# we install with the daemon disabled, the configure hook
# will start and enable it if appropriate
snapctl stop --disable "$SNAP_INSTANCE_NAME.daemon"

daemon=$(snapctl get daemon)
if [ "$daemon" = "" ]
then
  snapctl set daemon=true
fi
